# Generated by Django 2.2.24 on 2021-10-22 06:47

import coprofile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия*')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя*')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество*')),
                ('work_place', models.TextField(blank=True, verbose_name='Место работы (полностью)*')),
                ('certificate_num', models.CharField(blank=True, max_length=30, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=coprofile.models.make_certificate_path, verbose_name='Сертификат')),
                ('speaker', models.BooleanField(default=False, verbose_name='Докладчик')),
                ('report_name', models.CharField(blank=True, max_length=250, verbose_name='Тема доклада*')),
                ('report_file', models.FileField(blank=True, null=True, upload_to=coprofile.models.make_upload_path, verbose_name='Файл научной статьи*')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('admin_access', models.BooleanField(default=False, verbose_name='Права администратора')),
                ('moderator_access', models.BooleanField(default=False, verbose_name='Права модератора')),
                ('message_accecc', models.BooleanField(default=False, verbose_name='Права рассылки оповещений')),
                ('lead', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
