# Generated by Django 2.2.19 on 2024-09-03 08:49

import coprofile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия*')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя*')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество*')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон*')),
                ('work_place', models.CharField(blank=True, max_length=250, verbose_name='Название организации*')),
                ('work_part', models.CharField(blank=True, max_length=250, verbose_name='Название отдела (факультет, кафедра)')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Занимаемая должность')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень, ученое звание')),
                ('certificate_num', models.CharField(blank=True, max_length=30, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=coprofile.models.make_certificate_path, verbose_name='Сертификат')),
                ('speaker', models.CharField(choices=[('1', 'Выступление с докладом'), ('2', 'Публикация статьи'), ('3', 'Участие без доклада')], default='3', max_length=1, verbose_name='Форма участия')),
                ('report_name', models.CharField(blank=True, max_length=250, verbose_name='Тема доклада*')),
                ('report_file', models.FileField(blank=True, null=True, upload_to=coprofile.models.make_upload_path, verbose_name='Файл научной статьи*')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('admin_access', models.BooleanField(default=False, verbose_name='Права администратора')),
                ('moderator_access', models.BooleanField(default=False, verbose_name='Права модератора')),
                ('message_accecc', models.BooleanField(default=False, verbose_name='Права рассылки оповещений')),
                ('lead', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
