# Generated by Django 2.2.19 on 2022-09-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученая степень, ученое звание'),
        ),
        migrations.AddField(
            model_name='coprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон*'),
        ),
        migrations.AddField(
            model_name='coprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Занимаемая должность'),
        ),
        migrations.AddField(
            model_name='coprofile',
            name='work_part',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название отдела (факультет, кафедра)'),
        ),
        migrations.AlterField(
            model_name='coprofile',
            name='speaker',
            field=models.BooleanField(choices=[('1', 'Выступление с докладом'), ('2', 'Публикация статьи'), ('3', 'Участие без доклада')], default='3', max_length=1, verbose_name='Форма участия'),
        ),
        migrations.AlterField(
            model_name='coprofile',
            name='work_place',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название организации*'),
        ),
    ]
