# Generated by Django 2.2.19 on 2025-01-31 20:14

import coprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coprofile', '0002_auto_20240903_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coprofile',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=coprofile.models.make_upload_path, verbose_name='Файл научной статьи  (при наличии)'),
        ),
    ]
