# Generated by Django 2.2.19 on 2026-02-02 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.TextField(blank=True, verbose_name='Какая информация была наиболее интересной и полезной для  Вас?')),
                ('answer_2', models.TextField(blank=True, verbose_name='Какие темы могут быть еще Вам интересны?')),
                ('answer_3', models.TextField(blank=True, verbose_name='Какие доклады и мастер - классы Вы могли бы предложить к проведению?')),
                ('done', models.BooleanField(default=False, verbose_name='Анкета сохранена')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ['user__profile__surname'],
            },
        ),
    ]
