# Generated by Django 2.2.19 on 2026-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_3',
            field=models.TextField(blank=True, verbose_name='Какие доклады и мастер-классы Вы могли бы предложить к проведению?'),
        ),
    ]
