# Generated by Django 2.2.16 on 2020-10-08 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Username:')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия*')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя*')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество*')),
                ('work_place', models.TextField(blank=True, max_length=30, verbose_name='Место работы (полностью)*')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации:')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
