# Generated by Django 2.2.16 on 2020-10-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='certificate_number',
            new_name='certificate_num',
        ),
    ]
