# Generated by Django 2.2.19 on 2024-09-03 08:54

from django.db import migrations, models
import profileuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=profileuser.models.make_upload_path, verbose_name='Файл научной статьи'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='report_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Тема доклада'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speaker',
            field=models.CharField(choices=[('1', 'Выступление с докладом (очно)'), ('4', 'Выступление с докладом (он-лайн))'), ('2', 'Публикация статьи'), ('3', 'Участие без доклада')], default='3', max_length=1, verbose_name='Форма участия'),
        ),
    ]
