# Generated by Django 2.2.16 on 2020-10-10 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_access',
            field=models.BooleanField(default=False, verbose_name='Права администратора'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
    ]
