# Generated by Django 2.2.16 on 2020-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_auto_20201026_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_accecc',
            field=models.BooleanField(default=False, verbose_name='Права рассылки оповещений'),
        ),
    ]
