# Generated by Django 2.2.19 on 2025-01-31 20:14

from django.db import migrations, models
import profileuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0003_auto_20240903_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=profileuser.models.make_upload_path, verbose_name='Файл научной статьи (при наличии)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speaker',
            field=models.CharField(choices=[('1', 'Выступление с докладом'), ('2', 'Участие без доклада')], default='2', max_length=1, verbose_name='Форма участия'),
        ),
    ]
