# Generated by Django 2.2.16 on 2020-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0003_auto_20201017_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moderator_access',
            field=models.BooleanField(default=False, verbose_name='Права администратора'),
        ),
    ]
