# Generated by Django 2.2.19 on 2025-02-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('profileuser', '0004_auto_20250131_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.Section'),
        ),
    ]
