# Generated by Django 2.2.16 on 2020-10-25 21:58

from django.db import migrations, models
import profileuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0004_profile_moderator_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=profileuser.models.make_upload_path, verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='moderator_access',
            field=models.BooleanField(default=False, verbose_name='Права модератора'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=profileuser.models.make_upload_path, verbose_name='Файл научной статьи*'),
        ),
    ]
