# Generated by Django 2.2.19 on 2025-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0005_profile_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_accecc',
            field=models.BooleanField(default=False, verbose_name='Права орг.комитета'),
        ),
    ]
