# Generated by Django 2.2.19 on 2026-02-01 13:26

from django.db import migrations, models
import profileuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0006_profile_org_accecc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to=profileuser.models.make_upload_path, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
