# Generated by Django 2.2.16 on 2020-10-26 08:41

from django.db import migrations, models
import profileuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0006_auto_20201026_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=profileuser.models.make_certificate_path, verbose_name='Сертификат'),
        ),
    ]
