# Generated by Django 2.2.19 on 2026-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0007_profile_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cookies_agree',
            field=models.BooleanField(default=False, verbose_name='Согласие с куки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='policy_success',
            field=models.BooleanField(default=False, verbose_name='Согласие c Политикой обработки персональных данных'),
        ),
    ]
